version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web_main
      - web_first

  web_main:
    container_name: web_main
    build:
      context: ./portfolio-main/main
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./portfolio-main/main:/home/app/web
    expose:
      - 8000
    env_file:
      - ./portfolio-main/main/.env.prod
      
  web_first:
    container_name: web_first
    build:
      context: ./portfolio-first/pastagram
      dockerfile: Dockerfile
    command: /home/app/web/entrypoint.sh
    volumes:
      - ./portfolio-first/pastagram:/home/app/web
    expose:
      - 8100
    env_file:
      - ./portfolio-first/pastagram/.env.prod
    depends_on:
      - db_first

  db_first:
    container_name: db_first
    image: postgres:12.0
    volumes:
      - postgres_data_first:/var/lib/postgresql/data/
    env_file:
      - ./portfolio-first/pastagram/.env.prod
    ports:
      - "5432:5432"
volumes:
  postgres_data_first:

